[package]
name = "gb_simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc_macros = { path = "proc_macros" }
derive_more = "0.99.17"
