pub const CART_TYPE_ROM_RAM_1: u8 = 0x08;
pub const CART_TYPE_ROM_RAM_BATTERY_1: u8 = 0x09;
pub const CART_TYPE_MMM01: u8 = 0x0B;
pub const CART_TYPE_MMM01_RAM: u8 = 0x0C;
pub const CART_TYPE_MMM01_RAM_BATTERY: u8 = 0x0D;

pub const CART_TYPE_MBC6: u8 = 0x20;
pub const CART_TYPE_MBC7_SENSOR_RUMBLE_RAM_BATTERY: u8 = 0x22;
pub const CART_TYPE_POCKET_CAMERA: u8 = 0xFC;
pub const CART_TYPE_BANDAI_TAMA5: u8 = 0xFD;
pub const CART_TYPE_HU_C3: u8 = 0xFE;
pub const CART_TYPE_HU_C1_RAM_BATTERY: u8 = 0xFF;
