[package]
name = "proc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro3 = { version = "0.1.1", features = ["proc-macro2"] }
syn = "2.0.37"
quote = "1.0.33"